version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.${APP_ENV}
    ports:
      - "80:80"
    depends_on:
      - db
      - mongo
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
  mongo:
    image: mongo:latest

